# Generated by Django 4.2.6 on 2024-02-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Home_app', '0004_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='offer_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
