# Generated by Django 4.2.6 on 2024-02-17 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0038_order_coupon_discount_order_coupon_valid_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User_Home_app', '0005_cart_offer_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_app.coupon')),
                ('customuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
