# Generated by Django 4.2.6 on 2024-02-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Home_app', '0007_wallet_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet_transactions',
            name='add_or_pay',
            field=models.CharField(default='add', max_length=100),
            preserve_default=False,
        ),
    ]
