# Generated by Django 4.2.9 on 2024-01-04 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0002_category_is_deleted_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_category',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Admin_app.category'),
        ),
    ]
