# Generated by Django 4.2.9 on 2024-01-04 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0003_alter_sub_category_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_category',
            old_name='Category',
            new_name='category',
        ),
    ]
