# Generated by Django 4.2.9 on 2024-01-05 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0004_rename_category_sub_category_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.BigIntegerField()),
                ('discound', models.DecimalField(decimal_places=2, max_digits=20)),
                ('stock', models.IntegerField()),
                ('description', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='media/product_imgs')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_app.sub_category')),
            ],
        ),
        migrations.CreateModel(
            name='Product_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(upload_to='media/product_imgs')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_app.product')),
            ],
        ),
    ]
