# Generated by Django 4.2.9 on 2024-01-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0005_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discound',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
