# Generated by Django 4.2.9 on 2024-01-23 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0009_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
