# Generated by Django 4.2.9 on 2024-01-29 07:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0014_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
