# Generated by Django 4.2.9 on 2024-01-31 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0019_alter_order_total_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order_items',
            options={'ordering': ['-id']},
        ),
    ]
