# Generated by Django 4.2.9 on 2024-01-31 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0020_alter_order_items_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id']},
        ),
    ]
