# Generated by Django 4.2.9 on 2024-02-04 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0021_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_items',
            name='Sub_Category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Admin_app.sub_category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order_items',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Admin_app.product'),
        ),
    ]
