# Generated by Django 4.2.6 on 2024-02-13 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0027_alter_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id']},
        ),
    ]
