# Generated by Django 4.2.6 on 2024-02-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0028_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_items',
            name='offer_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
