# Generated by Django 4.2.6 on 2024-02-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0030_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
