# Generated by Django 4.2.6 on 2024-02-15 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0031_offer_is_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_app.sub_category')),
                ('offers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin_app.offer')),
            ],
        ),
        migrations.AddField(
            model_name='sub_category',
            name='offer',
            field=models.ManyToManyField(blank=True, related_name='offer', through='Admin_app.OfferCategory', to='Admin_app.offer'),
        ),
    ]
