# Generated by Django 4.2.6 on 2024-02-15 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0032_offercategory_sub_category_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_category',
            name='offer',
        ),
        migrations.DeleteModel(
            name='OfferCategory',
        ),
    ]
