# Generated by Django 4.2.6 on 2024-02-15 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0033_remove_sub_category_offer_delete_offercategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_category',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Admin_app.offer'),
        ),
    ]
