# Generated by Django 4.2.6 on 2024-02-15 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0034_sub_category_offer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='sub_category',
            options={'ordering': ['-id']},
        ),
    ]
