# Generated by Django 4.2.6 on 2024-02-16 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0036_coupen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coupen',
            new_name='Coupon',
        ),
    ]
