# Generated by Django 4.2.6 on 2024-02-21 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin_app', '0038_order_coupon_discount_order_coupon_valid_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
