# Generated by Django 4.2.9 on 2024-01-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_customuser_ph_no_alter_customuser_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_address',
            name='location',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_address',
            name='pin_code',
            field=models.TextField(verbose_name='Postal Code'),
        ),
    ]
