# Generated by Django 4.2.9 on 2024-01-21 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_user_address_location_alter_user_address_pin_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Address',
        ),
    ]
