# Generated by Django 4.2.9 on 2024-01-23 07:58

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_address',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
