# Generated by Django 4.2.9 on 2024-01-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_alter_user_address_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_address',
            name='phone',
            field=models.CharField(),
        ),
    ]
