# Generated by Django 4.2.9 on 2024-01-31 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_alter_user_address_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='user_address',
            options={'ordering': ['-id']},
        ),
    ]
